### ISSUE TITLE
Feature | 支持「文档树结构」和「平铺」两种展示模式

### ISSUE THREAD

**Issue by frostime** [syh19/siyuan-plugin-task-list#1]
- 现状：目前的展示方式是按照「文档树结构」来展示对应文档下的 TODO
- 问题：但是在文档结构较为复杂的情况下，过多的文档结构反而成为了干扰，导致有效信息密度降低（因为很多情况下可能我们并不在意任务列表来自哪个文档中）
- 建议：支持「平铺」显示模式，不显示文档，而是单纯将所有的代办列表平铺显示

**Comment by syh19** [comment]
> * 现状：目前的展示方式是按照「文档树结构」来展示对应文档下的 TODO
> * 问题：但是在文档结构较为复杂的情况下，过多的文档结构反而成为了干扰，导致有效信息密度降低（因为很多情况下可能我们并不在意任务列表来自哪个文档中）
> * 建议：支持「平铺」显示模式，不显示文档，而是单纯将所有的代办列表平铺显示

感谢反馈，后续会增加【树状数据】和【平铺列表数据】两种不同的表现形式相互切换的功能。

**Comment by syh19** [comment]
@frostime 
【树状数据视图】以及【列表视图】的切换功能已在`v0.0.5`版本添加，如果还有别的需求欢迎随时反馈，谢谢 🙏
