### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by initthd** [syh19/siyuan-plugin-task-list#10]
安卓平板是否支持使用，貌似侧边栏不出来，感谢

**Comment by syh19** [comment]
@initthd 
抱歉哈，目前这个版本限制了只能在PC端使用，下个版本我会放开只有PC端的限制，下个版本尽快发布哈

**Comment by syh19** [comment]
@initthd 
插件在`V0.0.4`版本中已经支持在移动端使用了，欢迎更新体验

**Comment by initthd** [comment]
> @initthd 插件在`V0.0.4`版本中已经支持在移动端使用了，欢迎更新体验

感谢，更新了，可用
