### ISSUE TITLE
是否需要排除下嵌入块的统计？

### ISSUE THREAD

**Issue by jokizhu** [syh19/siyuan-plugin-task-list#11]
文档中，若有任务列表，也有嵌入式块，嵌入式块里边关联文档中的任务列表，使用该任务插件，搜索到内容可能是嵌入式块，点击跳转是嵌入式块，预期跳转应该是真实任务列表位置，这个能过滤下么，感谢~

**Comment by syh19** [comment]
@jokizhu 
您好，目前的【任务列表】中是搜索不到嵌入块里面的任务的，列出的就是真实的任务节点，通过点击进行定位也是跳转到真实的位置。下图是我刚刚测试的效果，您所说的问题暂时没有复现。如果能够稳定复现的话，能否告知一下具体的操作步骤。

<img width="1435" alt="image" src="https://github.com/syh19/siyuan-plugin-task-list/assets/47665360/727a2a1e-d846-4214-ada2-83adc3211043">

**Comment by jokizhu** [comment]
![Uploading 2024-03-29-14-58-08.gif…]()
这是我这边效果，跳转是嵌入式块列表

**Comment by jokizhu** [comment]
![Uploading 2024-03-29-14-58-08.gif…]()
[任务列表测试.sy.zip](https://github.com/syh19/siyuan-plugin-task-list/files/14800754/sy.zip)
![image](https://github.com/syh19/siyuan-plugin-task-list/assets/128120301/dfc442cb-72af-4bcd-b821-afddf36b58b2)

**Comment by jokizhu** [comment]
貌似看出差异了，你把嵌入式块放在上边，真实列表放在下边，应该和我这边效果一样，会被定为到嵌入块中

**Comment by syh19** [comment]
> 貌似看出差异了，你把嵌入式块放在上边，真实列表放在下边，应该和我这边效果一样，会被定为到嵌入块中

我导入了您的压缩包，复现问题了，感谢反馈，大概知道原因了，这个问题我会尽快修复的

**Comment by syh19** [comment]
已在`v0.0.3`版本中修复
