### ISSUE TITLE
count open tasks

### ISSUE THREAD

**Issue by Dayflare** [syh19/siyuan-plugin-task-list#14]
i really like the task list addon, it gives a good overview.

It would be very nice if there was a counter which counts the open tasks.

**Comment by syh19** [comment]
@Dayflare 
Thank you for liking this plugin. Task counter is a great idea. I will implement this feature as soon as possible.

**Comment by syh19** [comment]
@Dayflare 
This new feature has been implemented in v0.1.3, welcome to update and experience it. If you encounter any problems during use, please provide feedback.
