### ISSUE TITLE
文档维度可以包含其下的子文档

### ISSUE THREAD

**Issue by OMEGA-jam** [syh19/siyuan-plugin-task-list#15]
在daliynote工作流中，任务节点通常散落在_“笔记本-年-月-日”_这一级文档中，现有的文档维度范围过小（只能涵盖单日），而笔记本维度又过大。
如果能够文档维度可以包含其下的子文档（如打开_月级文档_可以看到该月内_日级文档_的任务节点汇总），使用起来会更方便。

另，本插件真的十分有用，极大辅助了我管理需做的任务，十分感谢作者的贡献！

**Comment by syh19** [comment]
@OMEGA-jam 您好，感谢您的反馈和建议。dailynote文档有其特殊性，后续会实现日历视图，可以基于指定日期或者指定日期范围对任务进行筛选。
相信这个筛选功能可以完美解决您对dailynote工作流程的支持。

**Comment by OMEGA-jam** [comment]
您对dailynote的理解比我更深刻！如果可以实现区域时间范围内的任务筛选，插件的易用性会再上一个台阶。

感谢您的回复，期待后续的更新！

**Comment by syh19** [comment]
@OMEGA-jam 
您好，日历视图筛选功能已经在`v0.2.0`版本实现并上架集市了，欢迎使用体验，如果后续还有问题欢迎随时反馈，谢谢。
