### ISSUE TITLE
任务列表是空的，开发者模式下看到报错信息

### ISSUE THREAD

**Issue by houzy** [syh19/siyuan-plugin-task-list#16]
现象：
任务列表是空的，未完成、完成、全部，都没有任何任务项显示。
开发者模式下报错信息：
plugin:siyuan-plugin-task-list:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'taskSortBy')
    at pT (plugin:siyuan-plugin-task-list:6:31961)
    at async b (plugin:siyuan-plugin-task-list:89:285783)

**Comment by syh19** [comment]
@houzy 您问您还能稳定复现这个报错吗？我试了好多遍没有复现出来。

**Comment by houzy** [comment]
能稳定复现，SiYuan版本是v3.0.11

**Comment by houzy** [comment]
重启思源笔记，列表是空的，昨天还是前天还是好的，昨天好像升级插件了，今天是空的。
![image](https://github.com/syh19/siyuan-plugin-task-list/assets/3501200/fd17bc66-556d-4037-80ce-a300e357f836)

**Comment by houzy** [comment]
插件版本号是：v.0.1.1

**Comment by syh19** [comment]
@houzy 我新建了个工作空间复现出来了，我争取今天尽快修复哈

**Comment by houzy** [comment]
好的，谢谢

**Comment by syh19** [comment]
@houzy 您好，`bug`已经在`v0.1.2`版本修复了，已经上架集市，您更新一下就可以了。这个`issue`我就先关闭了，如果后续还有问题欢迎随时反馈，谢谢。
