### ISSUE TITLE
关于设置中排序方式的选择

### ISSUE THREAD

**Issue by houzy** [syh19/siyuan-plugin-task-list#17]
在设置界面中，有排序方式的下拉框，可以选择按创建时间升序、降序等方式，但是我选择后，没有发现展示上有什么区别，请问这个功能是怎么使用的？

**Comment by syh19** [comment]
@houzy 
请问一下您选择的**任务列表的展示方式**是哪一种呀，目前`笔记本 & 文档 & 任务`模式排序可能无效，您可以先使用`笔记本 & 任务`模式。
另外具体的排序逻辑您可以参考一下[这篇帖子](https://ld246.com/article/1713763068272)。

**Comment by houzy** [comment]
明白了，我是笔记本 & 文档 & 任务模式，所以没有作用。谢谢解答。
