### ISSUE TITLE
安卓手机应用端的支持

### ISSUE THREAD

**Issue by littlewhitepaper** [syh19/siyuan-plugin-task-list#18]
能否增加安卓手机的插件使用，本插件用着实在舒心！

**Comment by syh19** [comment]
@littlewhitepaper 
您好，感谢喜欢和支持。这个插件已经支持在移动端使用了。
![Screenshot_2024-05-01-10-36-09-022_org.b3log.siyuan.jpg](https://github.com/syh19/siyuan-plugin-task-list/assets/47665360/ab5097f1-f0d5-4115-a5fb-83f920a54ef5)

不过移动端因为没有显示**集市**，您需要通过移动端伺服，用网页打开移动端伺服的服务地址，通过网页上的**集市**下载这个插件，然后就可以在移动端使用了。

**Comment by syh19** [comment]
@littlewhitepaper 
您好，感谢喜欢和支持。这个插件已经支持在移动端使用了。
![Screenshot_2024-05-01-10-41-12-680_org.b3log.siyuan.jpg](https://github.com/syh19/siyuan-plugin-task-list/assets/47665360/2906cb5c-0512-4703-847c-19992043a15d)



不过移动端没有显示集市，您需要通过移动端伺服，用网页打开移动端伺服的服务地址，通过网页上的集市下载这个插件，然后就可以正常在移动端使用了。

**Comment by littlewhitepaper** [comment]
感谢回复！再次查看发现已经可以使用了！
![微信图片_20240501133349](https://github.com/syh19/siyuan-plugin-task-list/assets/126491733/2bd9ae42-e351-464d-ae74-2d261a20aae1)
