### ISSUE TITLE
任务排序设置没有生效

### ISSUE THREAD

**Issue by lovelife88** [syh19/siyuan-plugin-task-list#19]
设置里的选项不起作用，无论如何设置，任务栏都是按创建时间升序排列。

**Comment by lovelife88** [comment]
任务列表按“笔记本 & 文档 & 任务”展示时不生效（都是按文档的创建时间升序排列），按“笔记本 & 任务”展示时生效。

**Comment by syh19** [comment]
> 任务列表按“笔记本 & 文档 & 任务”展示时不生效（都是按文档的创建时间升序排列），按“笔记本 & 任务”展示时生效。

目前排序确实还有点问题，在修复前您可以先这么过渡下，我会尽快修复的。

**Comment by syh19** [comment]
@lovelife88 
您好，bug 在v0.1.4版本修复了，已经上架集市，您更新一下就可以了。这个issue我就先关闭了，如果后续还有问题欢迎随时反馈，谢谢。
