### ISSUE TITLE
BUG | 展开收起按钮的状态与实际情况不同步

### ISSUE THREAD

**Issue by TCOTC** [syh19/siyuan-plugin-task-list#2]
比如：

1. 在笔记本「展开」后按钮变为「收起」，切换到工作空间后按钮仍然是「收起」，此时要先点「收起」再点「展开」才能展开
2. 在点击「展开」后按钮变为「收起」，再点击「刷新」之后实际状态变为收起，而按钮上仍然是「收起」，此时要先点「收起」再点「展开」才能展开

![image](https://github.com/syh19/siyuan-plugin-task-list/assets/78434827/30d70c29-e656-4ffa-ba98-bb4d38bb0822)

**Comment by syh19** [comment]
> 比如：
> 
> 1. 在笔记本「展开」后按钮变为「收起」，切换到工作空间后按钮仍然是「收起」，此时要先点「收起」再点「展开」才能展开
> 2. 在点击「展开」后按钮变为「收起」，再点击「刷新」之后实际状态变为收起，而按钮上仍然是「收起」，此时要先点「收起」再点「展开」才能展开
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/316284804-30d70c29-e656-4ffa-ba98-bb4d38bb0822.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNTgyODUsIm5iZiI6MTcxMTI1Nzk4NSwicGF0aCI6Ii83ODQzNDgyNy8zMTYyODQ4MDQtMzBkNzBjMjktZTY1Ni00ZmZhLWJhOTgtYmI0ZDM4YmIwODIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA1MjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZDExZDY2MDczMWRjMzdhMjBiOTVkMTEwMmIyMTM5ZjVmOTVkMWQxYmE0NzJkOGNiMjgyMmY1OTQ4ODMwMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N01C9n-cicmgp6aoHWFTpg_3P50M16WsivEBF2Qaf9E)

感谢反馈，目前确实存在这个问题，我会尽快修复这个问题。

修复方案为：根据当前按钮所表现的【展开】或者【收起】状态，在切换TAB或者刷新数据后，将数据的实际展开收起状态和按钮保持一致。

**Comment by syh19** [comment]
@TCOTC 
这个bug已经在`v0.0.2`版本修复，这个`issue`就关闭了。
