### ISSUE TITLE
关于右上角菜单栏重影的问题

### ISSUE THREAD

**Issue by yikexiaoyao** [syh19/siyuan-plugin-task-list#22]
![PixPin_2024-06-12_13-09-36](https://github.com/syh19/siyuan-plugin-task-list/assets/36374114/8b4ad072-1434-4fed-91e0-a75ad352f3c3)

鼠标悬停或点击时出现

**Comment by syh19** [comment]
好哒，感谢反馈，下个版本修复一下。

**Comment by syh19** [comment]
这个问题已经在`v0.2.6`版本修复了，更新一下就好啦。
