### ISSUE TITLE
设置任务处理时间，控制台会报错

### ISSUE THREAD

**Issue by 397334469** [syh19/siyuan-plugin-task-list#28]
![image](https://github.com/syh19/siyuan-plugin-task-list/assets/51410244/baaf116f-8416-458a-98ca-59e9bceef84d)

![image](https://github.com/syh19/siyuan-plugin-task-list/assets/51410244/6addc662-5ea9-4b15-8fb3-8989c346abfc)

**Comment by syh19** [comment]
好的好的，感谢反馈，我尽快修复下。
