### ISSUE TITLE
任务筛选无法跨月，建议允许用户直接修改时间

### ISSUE THREAD

**Issue by 397334469** [syh19/siyuan-plugin-task-list#29]
![image](https://github.com/syh19/siyuan-plugin-task-list/assets/51410244/3a4c2881-cce3-427b-ace5-8d7997824ac5)

**Comment by syh19** [comment]
<img width="798" alt="image" src="https://github.com/syh19/siyuan-plugin-task-list/assets/47665360/62f7074a-4531-43dc-997f-be6ec765984e">

您好，这个是可以跨月的，首先点击起始日期，然后点击上方的左右箭头切换月份，最后再点击结束日期就可以实现跨月筛选了。

**Comment by 397334469** [comment]
感谢回复，已可以选择跨月。在选择日期过程中，有发现任务不包含结束日期。不知道是不是BUG。
![image](https://github.com/syh19/siyuan-plugin-task-list/assets/51410244/a57e4c29-7a45-4fd0-b6f8-720b54a6146c)
![image](https://github.com/syh19/siyuan-plugin-task-list/assets/51410244/008a4bec-0b5f-4a64-a219-00230e788fca)

**Comment by syh19** [comment]
> 感谢回复，已可以选择跨月。在选择日期过程中，有发现任务不包含结束日期。不知道是不是BUG。 ![image](https://private-user-images.githubusercontent.com/51410244/344508797-a57e4c29-7a45-4fd0-b6f8-720b54a6146c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3OTc2MzQsIm5iZiI6MTcxOTc5NzMzNCwicGF0aCI6Ii81MTQxMDI0NC8zNDQ1MDg3OTctYTU3ZTRjMjktN2E0NS00ZmQwLWI2ZjgtNzIwYjU0YTYxNDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAxMjg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNzVmMzdjODgwNTcxOWZiZjgyODRjZTgzNjk2NzM0ZGY0OTAxOTAxYzlhMGEyZDAxNzczOTM0YzcxOTIwYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2daL6xMHyZCu6lsnMzExLzPM59YVAzZET3C3s9KJcSg) ![image](https://private-user-images.githubusercontent.com/51410244/344508870-008a4bec-0b5f-4a64-a219-00230e788fca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3OTc2MzQsIm5iZiI6MTcxOTc5NzMzNCwicGF0aCI6Ii81MTQxMDI0NC8zNDQ1MDg4NzAtMDA4YTRiZWMtMGI1Zi00YTY0LWEyMTktMDAyMzBlNzg4ZmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAxMjg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMGEzNTA5NjU4ZjIyZjMxOTY5M2ZmN2I5N2VmMzk1ZTFhODZkZThmZjgyNzhlMTY5NDhlYjE2NmE1NDZhNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C4iQ1NEuzj0N9ekITkKkF7oS3_3uXa3YUuHOEo-wojo)

好的，感谢反馈，这个问题我修复下哈。

**Comment by syh19** [comment]
已经在`v0.3.3`版本修复啦，欢迎更新体验，如果后续使用过程中还有问题，欢迎随时反馈，谢谢。
