### ISSUE TITLE
调整深色模式下部分配色

### ISSUE THREAD

**Issue by actforjason** [syh19/siyuan-plugin-task-list#32]
字体颜色不明显
![image](https://github.com/user-attachments/assets/cbb607c1-9abd-4143-a894-3ed048403cb8)

**Comment by syh19** [comment]
好嘞，我改一下配色哈，下个版本修复下。

**Comment by syh19** [comment]
已经在`v0.4.2`版本修复啦，欢迎更新体验，如果后续使用过程中还有问题，欢迎随时反馈，谢谢。
