### ISSUE TITLE
希望实现针对于单个任务块的选择性显示

### ISSUE THREAD

**Issue by gingde** [syh19/siyuan-plugin-task-list#34]
有些任务块只是为了排版需要，使用任务块的形式看起来好看。
但是并不是需要后续显示在任务块汇总里面，不需要后续跟进。

现在的的方案是对于部分的笔记提供隐藏的功能。
但是这个方案不够灵活，且一个文档里面存在有些想要跟进 有些只是为了排版好看的情况。这样的话就无法区分
且任务块的使用比较灵活，特意去区分 不太合适，浪费时间

我希望能做到针对于单个任务块 的隐藏显示。

**Comment by syh19** [comment]
好的，后续会支持单个任务的**隐藏和显示**，不过近期事情比较多，可能会较晚实现这个功能。

**Comment by syh19** [comment]
这个功能已经在`v1.0.8`版本实现啦，欢迎使用体验。
