### ISSUE TITLE
切换日夜间模式图标不显示

### ISSUE THREAD

**Issue by 5kyfkr** [syh19/siyuan-plugin-task-list#4]
如下图，切换主题日夜间模式后图标不显示
![image](https://github.com/syh19/siyuan-plugin-task-list/assets/63196026/ac14d8b6-3d25-482c-a24d-de017fa02dea)

**Comment by syh19** [comment]
@5kyfkr 
感谢反馈，我排查下原因。
切换日夜间模式后，在重建索引后就会正常显示图标了，在bug修复前您可以先这么过渡下，感谢理解。

**Comment by syh19** [comment]
该问题已在`v1.0.3`版本修复。
