### ISSUE TITLE
希望可以加入更多筛选功能，比如按日期筛选等

### ISSUE THREAD

**Issue by xiaomingyu-git** [syh19/siyuan-plugin-task-list#7]
不得不说，这个插件真的是太实用了！！！非常感谢。
希望更多的筛选，
![image](https://github.com/syh19/siyuan-plugin-task-list/assets/44595719/6a9b3fc1-e2ec-46d3-aac8-2c515c455d95)
希望加入比如点击日期，看这个日期对应的任务列表等等更多筛选功能

**Comment by syh19** [comment]
@xiaomingyu-git 
好嘞，感谢提议，后续迭代会增加这个功能的。
非常感谢支持和喜欢~

**Comment by syh19** [comment]
@xiaomingyu-git 
您好，日历视图筛选功能已经在`v0.2.0`版本实现并上架集市了，欢迎使用体验，如果后续还有问题欢迎随时反馈，谢谢。
