### ISSUE TITLE
能否出个使用说明，比如怎么操作才能添加一个任务

### ISSUE THREAD

**Issue by houzy** [syh19/siyuan-plugin-task-list#8]
能否出个使用说明，比如怎么操作才能添加一个任务。看功能说明是自己想要的，但是不知道怎么将内容添加到任务列表中。

**Comment by syh19** [comment]
@houzy 
您好，**任务列表**插件不负责添加任务，只是用来搜集汇总您在思源笔记中添加的任务节点。
添加任务是**思源笔记**本身的功能的，具体如何操作您可以查看《思源笔记用户指南》关于**任务**的介绍。
下图是相关的介绍，您可以打开对应的文档具体实践下，不难的。然后刷新之后您就可以在**任务列表**插件中看到您刚刚创建好的任务了。

![tasknode](https://github.com/syh19/siyuan-plugin-task-list/assets/47665360/473e841b-3059-438a-80fb-7442272f464d)

**Comment by houzy** [comment]
感谢答复，我明白了，只要是任务块，就会被扫描到任务列表中，只是扫描的有点慢。我新添加一个任务，要过上一会儿才能看到，点击那个刷新按钮也不行，过了一会儿出现了。
