### ISSUE TITLE
待办的顺序

### ISSUE THREAD

**Issue by meinCF** [syh19/siyuan-plugin-task-list#9]
您好啊 感谢您制作的待办插件

关于待办的顺序 据我观察是在最新创建的文档在最上面 最新创建的待办在最上面 
不知能否实现自定义排序或者按名称排序呢 

一个小提议~

祝您生活愉快。

**Comment by syh19** [comment]
@meinCF 
感谢支持和喜欢，目前准备先做对任务的过滤隐藏功能了，排序功能也是很重要的，会尽快安排的哈

目前的顺序是按照创建时间倒序排列的

**Comment by syh19** [comment]
排序功能在`v0.1.0`版本实现啦，如果在使用过程中遇到什么问题或者有好的建议欢迎随时反馈。
